INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('AdminOne','Primary','ap@apple.com','SRE','ACTIVE','superadmin','$2a$10$blA/cFrvJDi8GGv7mb.N/u5uD3tT7i8GaQC4/29VaUiRKV.FDx3hi',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('AdminTwo','Secondary','as@apple.com','SRE','ACTIVE','admin','$2a$10$tEbLEGuhgjpD8tOQViquc.1XaAYnwo6r4XYg93tNyI/BvQNW39cMa',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('John','Doe','johndoe@apple.com','OPM','ACTIVE','opm1','$2a$10$AjnlaTR6jFkIoKrjIwK8ROW6MnjRJlV4vvR2HJn5zbUyif4WTbKYC',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('Jane','Dorsy','jdorsy@apple.com','OPM','ACTIVE','opm2','$2a$10$Lpv2UglEiVBMKqFLex.uDejDiOtIPRSfL7Jn2mqI5ZxNq8bKsqKPS',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('DEV 1','Granger','dev1@apple.com','DEV','ACTIVE','dev1','$2a$10$2jWHHX63k5Ya.dOscALw/OCe9V1x68P1WEzqse9nhL0r4SNyPSqIS',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('DEV 2','Zeta','dev2@apple.com','DEV','ACTIVE','dev2','$2a$10$8ZbMmMQxpYLbJ2j3ES5Ve.rHQDWvxB6e9md2TfRpHzZ2RiuMvoSOm',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('EPM 1','Wagner','epm1@apple.com','EPM','ACTIVE','epm1','$2a$10$h7FFag1j21/GfXJOArbUQOVuaEAPKrZGhWHfwXKXvQz2OIV84slH2',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('EPM 2','Jackson','epm2@apple.com','EPM','ACTIVE','epm2','$2a$10$ito.vsKLZ.Zhv4QomCec3.ZmRwZCAbVkYDEz/6vVWeNAQbhzo59hS',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('SRE1','SRE','sre1@apple.com','SRE','ACTIVE','sre1','$2a$10$qC1Azz33lET9dhSkPEbtaeDyihRbTTh4Y2mf5yU.wylA1xb8rfluO',true);
INSERT INTO PERSON(FIRST_NAME,LAST_NAME,EMAIL,TEAM,STATUS,USERNAME,PASSWORD,ACCOUNT_NON_LOCKED) VALUES('OPS1','OPS','ops1@apple.com','OPS','ACTIVE','ops1','$2a$10$Bw4R.asn0m5gEZ5vGeIXYO0cU1aSJbSHuXpoOM9/anUAEQXrGBz5m',true);

INSERT INTO ROLE(CODE) VALUES('ADMIN');
INSERT INTO ROLE(CODE) VALUES('OPM');
INSERT INTO ROLE(CODE) VALUES('DEV');
INSERT INTO ROLE(CODE) VALUES('EPM');
INSERT INTO ROLE(CODE) VALUES('SRE');
INSERT INTO ROLE(CODE) VALUES('OPS');

INSERT INTO PERSON_ROLES VALUES(1,1);
INSERT INTO PERSON_ROLES values(1,2)
INSERT INTO PERSON_ROLES VALUES(2,1);
INSERT INTO PERSON_ROLES VALUES(3,2);
INSERT INTO PERSON_ROLES VALUES(4,2);
INSERT INTO PERSON_ROLES VALUES(5,3);
INSERT INTO PERSON_ROLES VALUES(6,3);
INSERT INTO PERSON_ROLES VALUES(7,4);
INSERT INTO PERSON_ROLES VALUES(8,4);
INSERT INTO PERSON_ROLES VALUES(9,5);
INSERT INTO PERSON_ROLES VALUES(10,6);

INSERT INTO SITE(CATEGORY,CITY,CODE,COMPANY,COUNTRY,INFRA,STATUS,PRODUCT_CATEGORIES,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('CM','SHANGHAI','FXZZ','FOXCONN','CHINA','LOCAL','ACTIVE','IPHONE','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO SITE(CATEGORY,CITY,CODE,COMPANY,COUNTRY,INFRA,STATUS,PRODUCT_CATEGORIES,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('CM','SHENZHEN','LXSZ','LUXSHARE','CHINA','LOCAL','ACTIVE','IPHONE,MAC','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO SITE(CATEGORY,CITY,CODE,COMPANY,COUNTRY,INFRA,STATUS,PRODUCT_CATEGORIES,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('CM','LONGGANG','BYLG','BYD','CHINA','LOCAL','ACTIVE','IPAD','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Skyline','FDR-DS','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('CA','FDR-CA','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Sealing','FDR-SS','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Tatsu','Spidercab','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Alder','Vinyl','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Aloha','Matchmaker','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Treecko','Provisioning','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Raptor','Activation','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Vega','Fusing','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Marina','Marina','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('Muhan','Muhan','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('HPS-Prov','Seacookie-Prov','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO APP(INTERNAL_NAME,EXTERNAL_NAME,STATUS,SRE_ID,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('HPS-Pair','Seacookie-Pair','ACTIVE',9,'ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('M38','MAC',2022,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('P55','IPHONE',2023,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('P57','IPHONE',2023,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('P71','IPHONE',2023,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('W75','WATCH',2022,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('A85','AUDIO',2022,'NPI','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(CODE,CATEGORY,YEAR_STARTED,STATUS,CREATED_BY,UPDATED_BY,CREATED_DATE,UPDATED_DATE) VALUES('L23','IPAD',2022,'MP','ADMIN','ADMIN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO CONFIG_TYPE(NAME) VALUES('NFAST-SEE');
INSERT INTO CONFIG_TYPE(NAME) VALUES('NFAST-KEYS');
INSERT INTO CONFIG_TYPE(NAME) VALUES('NFAST-KEYS-EC');
INSERT INTO CONFIG_TYPE(NAME) VALUES('BINARY');
INSERT INTO CONFIG_TYPE(NAME) VALUES('JMET-ANSIBLE');

INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(1,1,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(1,2,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(1,3,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(2,1,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(2,2,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(2,3,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(2,4,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(3,5,'PRODUCTION','127.0.0.1');
INSERT INTO SITE_APP(SITE_ID,APP_ID,ENVIRONMENT,VIP) VALUES(3,6,'PRODUCTION','127.0.0.1');